

<form method='POST' enctype="multipart/form-data" class='userConnect'>

        <div>
            <select id='type' name="type">
            <option value="Appartement">Type de bien immobilier</option>
                <option value="Appartement">Appartement</option>
                <option value="Maison">Maison</option>
                <option value="Commerce">Commerce</option>
            </select>
        </div>

        <div>
            <input type="text" id="typeBien" name="typeBien" placeholder="Type d'appartement">
        </div>

        <div>
             <textarea id="Description" name="Description" placeholder="Desciption" rows="5" cols="33"></textarea>
        </div>
      
        <div>
            <input type="text" id="city" name="city" placeholder="Ville">
        </div>

        <div>
            <input type="text" id="departement" name="departement" placeholder="Département">
        </div>

        <div>
            <input type="text" id="area" name="area" placeholder="Surface">
        </div>

        <div>
            <input type="text" id="surfaceHabitable" name="surfaceHabitable" placeholder="Surface habitable">
        </div>

        <div>
            <input type="text" id="nombrePiece" name="nombrePiece" placeholder="Nombre de piéces">
        </div>

        <div>
            <input type="text" id="TypeConstruction" name="TypeConstruction" placeholder="Type de construction">
        </div>
        
        <div>
            <input type="text" id="AnneeConstruction" name="AnneeConstruction" placeholder="Année de construction">
        </div>

        <div>
            <input type="text" id="price" name="price" placeholder="prix">
        </div>

        <div>
            <input type="text" id="ProvisionCharge" name="ProvisionCharge" placeholder="Provision charge">
        </div>

        <div>
            <input type="text" id="TravauxRecent" name="TravauxRecent" placeholder="Travaux recent">
        </div>
        
        <div>
            <input type="text" id="TravauxProvisoir" name="TravauxPrevoir" placeholder="Travaux à prévoir">
        </div>

        <div>
            <input type="text" id="HnoraireCharge" name="HnoraireCharge" placeholder="Honoraire charge">
        </div>

        <div>
            <input type="text" id="constitutionDossier" name="constitutionDossier" placeholder="Constitution du dossier">
        </div>

        <div>
            <input type="text" id="EtatDesLieux" name="EtatDesLieux" placeholder="Etat des lieux">
        </div>

        <div>
            <input type="text" id="depotGarantie" name="depotGarantie" placeholder="Dépot de garantie">
        </div>

        <div>
            <input type="text" id="chauffage" name="chauffage" placeholder="Chauffage">
        </div>
        
        <div>
            <input type="text" id="EauChaude" name="EauChaude" placeholder="Eau chaude">
        </div>

        <div>
              <label for='Picturs1' class='custom_file_upload'>Photo (1)</label>
                <input type="file" name="Picturs1" id="Picturs1">
         </div>

         <div>
                <label for='Picturs2' class='custom_file_upload'>Photo (2)</label>
                <input type="file" name="Picturs2" id="Picturs2">
         </div>

         <div>
                <label for='Picturs3' class='custom_file_upload'>Photo (3)</label>
                <input type="file" name="Picturs3" id="Picturs3">
         </div>

         <div>
                <label for='Picturs4' class='custom_file_upload'>Photo (4)</label>
                <input type="file" name="Picturs4" id="Picturs4">
         </div>

         <div>
                <label for='Picturs5' class='custom_file_upload'>Photo (5)</label>
                <input type="file" name="Picturs5" id="Picturs5">
         </div>
         
         <div>
                <label for='Picturs6' class='custom_file_upload'>Photo (6)</label>
                <input type="file" name="Picturs6" id="Picturs6">
         </div>
          
        <button type="submit">Publier</button>
        <button type="reset"><a href="user.php?id="<?= intval($_SESSION['id_user']); ?>>Annuler</a></button>
    </form>
    
