

        <section class='aPropos'>
            <p>Aven les 1200 agences en France Le réseau ID.HALLES, premier réseau d'agences
                 immobiliéres. Vous acceuille prés de chez vous dans l'une de ses 1200
                agences réparties dans toute le France. Rien ne remplace l'expertise 
                immobiliére de proximité de nos conseilliers imobiliers qui vous guideront 
                et vous conseillerons dans votre choix. Ainsi, n'hésitez pas à les contacter 
                pour convenir d'un rendez-vous directement dans l'agence immobiliére la plus 
                proche de chez vous.</p>
        </section>
    

    