    
        <section id='picturAttachement'>

           <form method='POST' class='formClassified'>

             <button id="location" type="button">Location</button>
             <button id="acheter" type="button">Acheter</button>

           </form>

           <section id="target">
               <h1>Vous souhaitez une estimation professionnelle ?</h1>
               <h2>Combien vaut votre bien ?</h2>
               <a href="estimation.php?id=<?php if(isset($userInfo)) {echo $userInfo['id_user'];}?>"><i class="fas fa-arrow-right"></i>Demandez un rendez-vous d'estimation gratuite</a>
           </section>

        </section>

        <section id='projetEnCour'>
            <h2>Nos projets en cour</h2>

            <article>
                <figure>
                    <img src='image/immeuble.jpg' alt='image de immeuble en cour de construction'>
                    <figcaption>Construction d'un immeuble</figcaption>
                </figure>

                <p>situé en centre ville de Boulogne comprenant 15 étages dont  
                 4 appartements par étage
                (plusieurs studios, appartement de type F4,F2 et en duplex de type F3).</p>
            </article><!--

            --><article>
                <figure>
                    <img src='image/cité.jpg' alt='image de cité en cour de construction'>
                    <figcaption>Construction d'une cité</figcaption>
                </figure>

                <p>Découvrez votre nouvelle résidence SYNAPSE située dans le quartier République
                     de Nanterre, ville résolument tournée vers l’avenir.
                     Vivez à 5 mn à pied de la vielle ville, avec ses commerces, ses restaurants,
                      son marché, son charme et son animation..</p>
            </article>

        </section>
        <section class='partenaires services'>
            <h3><em>Faite votre choix parmis tout nos programmes immobilier <span>neufs partout en france</span>
               et bénificiez <span>de nombreux avantages :</span></em></h3>

               <article>
               <i class="fas fa-edit"></i>
                    <p>Une <strong>personnalisation</strong> à la carte</p>
               </article><!--

                   --><article>
                   <i class="fas fa-file-invoice-dollar"></i>
                    <p><strong>Frais de notaire</strong> reduits</p>
               </article><!--

                   --><article>
                   <i class="fas fa-lock-open"></i>
                    <p>Un <strong>achta</strong> sécurisé</p>
               </article>

        </section>

        <section class='partenaires'>
            <h2>Nos partenaires</h2>

            <figure>
                <img src='image/logoPartenaire(3)' alt='logo du partenaire (1)'>
                <figcaption>ICC</figcaption>
            </figure><!--

            --><figure>
                <img src='image/logoPartenaire(1)' alt='logo du partenaire (2)'>
                <figcaption>COMPANY IMMOBILIER</figcaption>
            </figure><!--

            --><figure>
                <img src='image/logoPartenaire(2)' alt='logo du partenaire (3)'>
                <figcaption>CREDITE IMMO</figcaption>
            </figure>

        </section>

    </main>

    
    


    